### PR TITLE
Update the DEPRECATION_WARNING to clarify cli vs OS deprecation

### PR DESCRIPTION
**Pull request by tianon**
cc @nathanleclaire

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks, LGTM :+1:

**Comment by nathanleclaire** [comment]
Looks reasonable, although I'd reduce slightly to:

```
  WARNING: The 'boot2docker' command line interface (not to be confused with
  'boot2docker' the operating system) is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.
```

**Comment by SvenDowideit** [comment]
LGTM @tianon can we merge this?

**Comment by tianon** [comment]
Oh man, this fell completely off my radar (thought it'd long since been taken care of).  Updated the message according to @nathanleclaire's suggestion.

**Comment by thaJeztah** [comment]
still LGTM (fwiw) :+1: :heart:

**Comment by tianon** [comment]
Let's get this off the stack; thanks for the prod, @SvenDowideit :+1:

**Comment by nathanleclaire** [comment]
Oh man, oops.  Haha.  LGTM

**Pull request merged**
