### PR TITLE
Fusion doesnt need vmware os addons

### PR DESCRIPTION
**Pull request by SvenDowideit**
replaces @jamtur01 and @zeeyang 's PR's

I've added code to get the first network device's IP address from the isc dhcpd's log files - now you don't need to have the vmware tools installed in the OS for it to work. (it tries the vmware tools first)

I've added the second eth device - the host only one to the vmx

@jamtur01 if you re-do your PR to separate your changes from @zeeyang 's, then I will rejig based on that, as I don't really feel thrilled about his work being subsumed into your commit.

### CODE REVIEW

**Comment by jamtur01** [comment]
You've taken all my changes so it's moot. LGTM

**Comment by zeeyang** [comment]
I'm working on a new lib that's meant to consolidate the effort around fusion/workstation. The goal is to have much better error handling and logging baked into the lib layer. https://github.com/zeeyang/fusia

Getting ip from dhcp lease table as a fall back is one of the things I'm planning on putting in the fusia lib, but it should also check if the NIC is `generated` vs `static` first. Can you guys hangs tight for a few days until the first release is ready?

**Comment by SvenDowideit** [comment]
@zeeyang oh, with pleasure!

**Comment by SvenDowideit** [comment]
@jamtur01 grrr, you mean you're forcing me to rebase your changes? thats mean!

**Comment by SvenDowideit** [comment]
mmm, intersting. the vmware dhcp server is sending an invalid nameserver when you add a second host only network.

**Comment by SvenDowideit** [comment]
actually, @zeeyang @tianon can we merge this as its useful today, and then move over to your new code when its ready? the UX should be the same.

**Comment by SvenDowideit** [comment]
Closing as #333 makes it clear b2d-cli is already in stasis.

**Pull request closed without merging**
