### PR TITLE
Improve removing the library path

### LINKED ISSUE #148: boot2docker-vm setup fails due to DYLD_LIBRARY_PATH settings
I downloaded the OS X installer. I'm running OS X 10.8.5 and VirtualBox 4.3.12.

My boot2docker-vm is not starting due to DYLD stuff in my environment. Seems to be an old problem for VBoxManage. 
Here's what I see for `boot2docker init -v`:

```
montag:~ $ boot2docker init -v
2014/06/09 17:11:10 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2014/06/09 17:11:10 Creating VM boot2docker-vm...
2014/06/09 17:11:10 executing: VBoxManage list vms
2014/06/09 17:11:10 executing: VBoxManage createvm --name boot2docker-vm --register
Virtual machine 'boot2docker-vm' is created and registered.
UUID: 4e832fce-2c78-46ac-a551-79de869e0351
Settings file: '/Users/montag/VirtualBox VMs/boot2docker-vm/boot2docker-vm.vbox'
2014/06/09 17:11:10 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2014/06/09 17:11:10 Apply interim patch to VM boot2docker-vm (https://www.virtualbox.org/ticket/12748)
2014/06/09 17:11:10 executing: VBoxManage setextradata boot2docker-vm VBoxInternal/CPUM/EnableHVP 1
2014/06/09 17:11:10 executing: VBoxManage modifyvm boot2docker-vm --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 8 --memory 1024 --vram 8 --acpi on --ioapic on --rtcuseutc on --cpuhotplug off --pae on --longmode on --synthcpu off --hpet on --hwvirtex on --triplefaultreset off --nestedpaging on --largepages on --vtxvpid on --vtxux off --accelerate3d off --uart1 0x3F8 4 --uartmode1 server /Users/montag/.boot2docker/boot2docker-vm.sock --boot1 dvd
2014/06/09 17:11:11 executing: VBoxManage showvminfo boot2docker-vm --machinereadable
2014/06/09 17:11:11 Setting NIC #1 to use NAT network...
2014/06/09 17:11:11 executing: VBoxManage modifyvm boot2docker-vm --nic1 nat --nictype1 virtio --cableconnected1 on
2014/06/09 17:11:11 executing: VBoxManage controlvm boot2docker-vm natpf1 ssh,tcp,127.0.0.1,2022,,22
2014/06/09 17:11:11 Port forwarding [ssh] tcp://127.0.0.1:2022 --> :22
2014/06/09 17:11:11 executing: VBoxManage controlvm boot2docker-vm natpf1 docker,tcp,127.0.0.1,2375,,2375
2014/06/09 17:11:11 Port forwarding [docker] tcp://127.0.0.1:2375 --> :2375
2014/06/09 17:11:11 executing: VBoxManage list hostonlyifs
2014/06/09 17:11:11 executing: VBoxManage list dhcpservers
2014/06/09 17:11:11 Creating a new host-only network interface...
2014/06/09 17:11:11 executing: VBoxManage hostonlyif create
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
2014/06/09 17:11:11 executing: VBoxManage hostonlyif ipconfig dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp --ip 192.168.59.3 --netmask 255.255.255.0
VBoxManage: error: The host network interface with the given name could not be found
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component Host, interface IHost, callee nsISupports
VBoxManage: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.asOutParam())" at line 218 of file VBoxManageHostonly.cpp
VBoxManage: error: Could not find interface 'dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp'
2014/06/09 17:11:11 Failed to create host-only network interface: exit status 2
```

I worked around the issue by doing

```
unset DYLD_LIBRARY_PATH
unset LD_LIBRARY_PATH
```
before `boot2docker init`.

Seems others calling VBoxManage have had to work around this issue as well - https://github.com/mitchellh/vagrant/issues/1258.

### PR DESCRIPTION
**Pull request by waltarix**
Fixes #148.

### CODE REVIEW

**Comment by tianon** [comment]
This one is back on the table now that we're on Go 1.4!

@waltarix still interested in carrying this one?  We'll likely have to remove the `- 1.3.3` from `.travis.yml` that I just added, but I'm OK with that, since this fixes a real issue.  I just wanted to make sure that removing Go 1.3 support became a conscious decision. :smile:

**Comment by waltarix** [comment]
Thank you for the good news! :grin:

Yes, I'm still interested in this one.
All right. Please let me know when Go 1.3 support is actually removed. then I'll rebase this PR.

**Comment by tianon** [comment]
I'd say that we might as well remove it here in this PR directly, since this is the feature we'd remove it for. :+1:

**Comment by waltarix** [comment]
I see.
Now I've created a new commit that removes Go 1.3 support, and also rebased!

**Comment by tianon** [comment]
Nice!  LGTM

cc @gmlewis @Moghedrin

**Comment by gmlewis** [comment]
LGTM

**Pull request merged**
