### PR TITLE
Add Fusion driver and vmx template

### PR DESCRIPTION
**Pull request by zeeyang**
Fusion driver for boot2docker-cli WIP...

### CODE REVIEW

**Comment by SvenDowideit** [comment]
ok, I've played with this a little, and its mostly working, so I'm going ot merge

**Comment by tianon** [comment]
...

**Comment by tianon** [comment]
Care to elaborate more on what "mostly working" means?  I'm specifically interested in what _isn't_ working, and would rather not merge things that aren't user-ready.

**Comment by SvenDowideit** [comment]
@tianon see the other 2 PR's - @jamtur01 resolved the error handling, and then in my new PR, I've made it work with the existing b2d.iso (ie, without needing the vmware tools)

I have noticed an intermittent issue with deleting - once the vmware gui gets involved, but otherwise, its been seriously solid.

**Comment by tianon** [comment]
Ok, that's more fair, but doesn't explain why it was necessary or appropriate to merge _this_ one, which has none of those improvements.

**Comment by SvenDowideit** [comment]
pretty simple - your LGTM from https://github.com/boot2docker/boot2docker-cli/pull/265#issuecomment-65122961 plus my having tested it, and both @jamtur01 and I having follow on PR's meant that I could _this_ and then get on with my work actually using it.

with `machine` hanging and crashing on my system, I'm looking for a non-pre-beta way to use existing TLS and non-TLS b2d iso's with fusion.

**Pull request merged**
